/**
 * crawlers.mjs — `robots.txt` and `llms.txt`: what this site tells a machine
 * that arrives without a browser (beads `addictedtoai-k1j`).
 *
 * ## Why `robots.txt` moved out of `app/robots.ts`
 *
 * It used to be six lines of `MetadataRoute.Robots` returning `allow: '/'` for
 * `*`. That is the correct *behaviour* and it was reached **by default rather
 * than by choice** — nothing in the file recorded that anyone had considered
 * who was being allowed in, and a reader of the served file saw a bare `Allow`
 * with no argument behind it.
 *
 * Next's robots generator cannot emit comments; `robots.txt` supports them and
 * every crawler ignores them. So the file is written here instead, as ordinary
 * text, and the reasoning travels **with the served artifact** rather than
 * living only in a source file no crawler operator will ever open. That is the
 * whole reason for the move: the decision is now legible at
 * `https://www.addictedtoai.net/robots.txt`.
 *
 * ## The decision itself
 *
 * **AI training and retrieval crawlers are allowed, deliberately, and named
 * one at a time.** `User-agent: *` already permits them, so naming them
 * changes no byte of behaviour — it changes what the file *records*. An
 * unnamed allow is indistinguishable from never having thought about it, and
 * the whole point of writing it down is that the next person to read this can
 * see a decision rather than a default.
 *
 * It is also the position that matches the site's own thesis. A record whose
 * every claim is dated and sourced to a primary document is written to be
 * quotable; being cited by an assistant is the most on-thesis channel this
 * site has, and it is the one that needs no social account, no outreach and no
 * human speaking on the site's behalf.
 *
 * **Reversing it is one line per crawler** — `Allow: /` becomes `Disallow: /`
 * in `AI_CRAWLERS` below — and the maintainer has been told so. That
 * cheapness is deliberate: a stance nobody can change without a redesign is
 * not a stance, it is a lock-in.
 *
 * ## What is deliberately NOT in `robots.txt`
 *
 * No `Disallow` for stubs or demoted tutorials, and this is the original
 * file's reasoning kept intact: per-page `noindex` lives in the page's own
 * meta tag, and a `Disallow` here would stop a crawler fetching the page at
 * all — so it would never read the tag, and the page would linger in an index
 * as a URL-only entry. Blocking the fetch is the one way to make `noindex`
 * not work.
 *
 * ## `llms.txt`
 *
 * The convention is a Markdown file at the root that tells a model where the
 * substance is. It points at the wiki as the substrate, the dataset, the
 * catalog and the feeds — **not at what the site would say about itself in a
 * pitch**. A model reading it wants the structured layer's URL and the licence
 * on it, in that order; marketing is noise that displaces both.
 *
 * Its counts are passed in and rendered, never asserted here, so the numbers
 * are the same ones the dataset payload carries — `scripts/verify-surfaces.mjs`
 * measures that they agree with the exported dataset rather than trusting it.
 */

import { SITE_NAME, SITE_TAGLINE, SITE_DESCRIPTION, absoluteUrl } from './site-config.mjs';
import {
  DATASET_JSON_ROUTE,
  DATASET_CSV_ROUTES,
  DATASET_CSV_LABELS,
  DATASET_LICENSE,
  DATASET_LICENSE_URL,
  TABLE_JSON_ROUTES,
  FEED_ROUTES,
  SEARCH_INDEX_ROUTE,
  STATUS_ROUTE,
  CONTRACT_ANCHOR,
} from './asset-routes.mjs';

/**
 * The AI crawlers this site has an explicit position on, and that position.
 *
 * `note` is printed into `robots.txt` beside the rule, so the served file says
 * what each token actually governs. Google-Extended in particular is **not a
 * crawler**: it is a token Google reads to decide whether already-crawled
 * pages may train Gemini or appear in AI answers, so a rule for it says
 * nothing about Googlebot and a reader who assumes otherwise has it backwards.
 *
 * `rule` is one word. Flipping any of these to `Disallow` is the entire
 * mechanism for reversing the stance for that crawler.
 */
export const AI_CRAWLERS = [
  { agent: 'GPTBot', rule: 'Allow', note: "OpenAI's training and retrieval crawler" },
  { agent: 'ClaudeBot', rule: 'Allow', note: "Anthropic's crawler" },
  { agent: 'PerplexityBot', rule: 'Allow', note: "Perplexity's search index" },
  {
    agent: 'Google-Extended',
    rule: 'Allow',
    note: 'not a crawler — the token governing Gemini training and AI Overviews',
  },
];

const RULE = (bot) => `${bot.rule}: /`;

/** The served `robots.txt`, comments and all. */
export function renderRobotsTxt() {
  const lines = [
    `# robots.txt — ${SITE_NAME}`,
    '#',
    '# Generated by the build (lib/crawlers.mjs). Editing the file in public/',
    '# does nothing: the next build overwrites it.',
    '#',
    '# EVERY crawler may read EVERY page, and that is a decision rather than a',
    '# default. There is no Disallow anywhere in this file, deliberately: pages',
    '# this site does not want indexed (data-only stubs, demoted tutorials,',
    '# discontinued tool listings) carry `noindex` in their own meta tag. A',
    '# Disallow here would stop a crawler fetching those pages at all, so it',
    '# would never read the tag — blocking the fetch is the one reliable way to',
    '# make noindex not work.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# --------------------------------------------------------------------------',
    '# AI TRAINING AND RETRIEVAL CRAWLERS',
    '#',
    '# The rule above already covers these. Naming them changes no behaviour at',
    '# all; it records that the question was asked. This site is a dated,',
    '# sourced record written to be quotable, and being cited by an assistant is',
    '# the channel that fits it best — so they are allowed on purpose.',
    '#',
    '# Any AI crawler not named below is covered by `User-agent: *` above and is',
    '# likewise allowed. The four here are the ones a position was taken on.',
    '# --------------------------------------------------------------------------',
  ];
  for (const bot of AI_CRAWLERS) {
    lines.push('', `# ${bot.note}`, `User-agent: ${bot.agent}`, RULE(bot));
  }
  lines.push('', `Sitemap: ${absoluteUrl('/sitemap.xml')}`, '');
  return lines.join('\n');
}

/**
 * The served `llms.txt`.
 *
 * @param {object} counts  the dataset's own `counts` object, passed through so
 *   this file and `/dataset/addictedtoai.json` state the same numbers.
 */
export function renderLlmsTxt(counts = {}) {
  const n = (key) => (Number.isFinite(counts[key]) ? counts[key] : null);
  const line = (route, label) => `- [${label}](${absoluteUrl(route)})`;
  const countLine = (key, noun) => {
    const v = n(key);
    return v === null ? null : `- **${v} ${noun}**`;
  };

  const out = [
    `# ${SITE_NAME}`,
    '',
    `> ${SITE_TAGLINE} ${SITE_DESCRIPTION}`,
    '',
    'This file exists so a model does not have to guess where the substance is.',
    'Everything below is a stable URL that a machine can read directly.',
    '',
    '## Start here: the structured layer',
    '',
    'The whole site is derived from one typed corpus. Take the corpus, not the',
    `pages. It is published under ${DATASET_LICENSE} (${DATASET_LICENSE_URL}), which asks`,
    'only for attribution, and the licence is stated inside every file as well as',
    'on the download page.',
    '',
    line(DATASET_JSON_ROUTE, 'Everything, as one JSON file'),
    ...Object.values(DATASET_CSV_ROUTES).map((route) => line(route, DATASET_CSV_LABELS[route])),
    '',
    'What is in it today:',
    '',
    countLine('entries', 'entries — one record per model, lab, tool, concept, technique, benchmark, dataset, paper or event'),
    countLine('facts', 'sourced facts, each with the URL it was read from and the date it was read'),
    countLine('timelines', 'dated, sourced lifecycle events'),
    countLine('catalog', 'model catalog rows — raw per-token prices and context windows'),
    countLine('deprecations', 'recorded deprecations and retirements'),
    countLine('deltas', 'dated impossible → routine pairs, both ends sourced'),
    '',
    '## How to read a claim on this site',
    '',
    'Every volatile value — a price, a context window, a status — is **bound**,',
    'never typed into prose: it is a feed fact or a transclusion resolved when the',
    'site is built, so it cannot go stale in a sentence. A value that vanished from',
    'its source renders as its last known value with a visible as-of date, and a',
    'value that was never known renders as absent rather than guessed. Dates are',
    'the local calendar date of the machine that wrote them.',
    '',
    '## The pages behind the data',
    '',
    'The wiki is the substrate; every other surface references it rather than',
    'restating its facts. If you need a citable URL for a claim rather than a row',
    'in a table, it is here.',
    '',
    line('/wiki', 'The wiki — one typed, sourced, dated record per thing in AI'),
    line('/catalog', 'The model catalog — prices and context windows, with the sort criterion stated'),
    line('/catalog/deprecations', 'Deprecations and retirements'),
    line('/catalog/changed', 'What changed, most recent first'),
    line('/tools', 'The curated tools directory, grouped by the job each tool does'),
    line('/learn', 'The learn ladder — the subject in order, orientation to advanced'),
    line('/tutorials', 'Tutorials, each verified against a stated version on a stated date'),
    line('/impossible-routine', 'Impossible → Routine — dated pairs, both ends sourced'),
    line('/blog', 'The blog'),
    line('/data', 'The download page, with the licence stated'),
    line('/colophon', 'How the site is made, and by what'),
    '',
    '## Live tables and feeds',
    '',
    'Every JSON payload below carries a `schema_version` and a `contract` field,',
    `and is served with \`Access-Control-Allow-Origin: *\`. What is stable and what`,
    `is deliberately not: ${absoluteUrl(CONTRACT_ANCHOR)}`,
    '',
    line(TABLE_JSON_ROUTES.catalog, 'The model catalog as JSON'),
    line(TABLE_JSON_ROUTES.deprecations, 'Deprecations and retirements as JSON'),
    line(TABLE_JSON_ROUTES.changed, 'What changed in the last 30 days, as JSON'),
    line(FEED_ROUTES.changes, 'What changed (RSS)'),
    line(FEED_ROUTES.blog, 'Blog (RSS)'),
    line(FEED_ROUTES.tutorials, 'Tutorials (RSS)'),
    line(SEARCH_INDEX_ROUTE, 'Every page name and title, including the data-only stubs'),
    line('/sitemap.xml', 'Every URL worth indexing, each with an honest last-modified date'),
    line(STATUS_ROUTE, 'The build stamp: which commit this deployment is serving'),
    '',
    '## Citing it',
    '',
    `${DATASET_LICENSE} — attribution to ${SITE_NAME} (${absoluteUrl('/')}). Individual pages`,
    'carry their sources: quote the primary document a fact links to in preference',
    'to quoting this site.',
    '',
  ];
  return out.filter((l) => l !== null).join('\n');
}
