#!/usr/bin/env bash
# Verify the routes lychee never crawls: the non-HTML ones, plus the
# custom 404. Run against a server already listening on $BASE.
#
#   npm run build && npm run start &
#   bash scripts/check-routes.sh
#
# Exits non-zero on the first failure, printing what it expected.
set -uo pipefail

BASE="${BASE:-http://localhost:3000}"
failures=0

check() {
  local path="$1" want_status="$2" want_type="$3" want_text="$4"
  local url="$BASE$path"
  local headers status ctype body

  headers=$(curl -s -o /dev/null -D - -w '%{http_code}' "$url")
  status="${headers##*$'\n'}"
  ctype=$(printf '%s' "$headers" | tr -d '\r' | grep -i '^content-type:' | head -1 | cut -d' ' -f2-)
  body=$(curl -s "$url")

  local problem=""
  [ "$status" = "$want_status" ] || problem="status $status (want $want_status)"
  case "$ctype" in
    *"$want_type"*) ;;
    *) problem="${problem:+$problem; }content-type '$ctype' (want *$want_type*)" ;;
  esac
  case "$body" in
    *"$want_text"*) ;;
    *) problem="${problem:+$problem; }body missing '$want_text'" ;;
  esac

  if [ -n "$problem" ]; then
    echo "FAIL  $path  -> $problem"
    failures=$((failures + 1))
  else
    echo "ok    $path  ($status, $want_type)"
  fi
}

#     path                     status  content-type  must contain
check /feed.xml                200 "rss+xml"   "<rss"
check /sitemap.xml             200 "xml"       "<urlset"
check /robots.txt              200 "text"      "Sitemap:"
check /manifest.webmanifest    200 "json"      '"start_url"'
check /icon.svg                200 "svg"       "<svg"
# The custom 404 must both report 404 and actually render the recovery
# page -- a soft 404 that returns 200 is its own SEO problem.
check /this-route-does-not-exist 404 "text/html" "Page not found"

# /log is generated by parsing CHANGELOG.md at build time. If a future
# entry is written in a shape the parser doesn't understand, the page
# still renders -- it just quietly loses rounds. Assert the round count
# so that failure is loud. Bump this when rounds are added.
echo
# Derive the expected count from the changelog itself rather than
# hardcoding a number that needs bumping every round -- a stale constant
# here would be the same "goes out of date" failure the log page exists
# to avoid.
#
# Counted by subtracting the template placeholder heading rather than by
# deleting the HTML comment block with a sed range: an entry that merely
# *mentions* "<!--" in its prose opens that range early and swallows the
# rest of the file. Which is exactly what happened -- this round's own
# entry quotes some rendered markup, and the first version of this check
# reported 1 round instead of 31.
all_headings=$(grep -c '^### ' CHANGELOG.md)
template_headings=$(grep -c '^### YYYY-MM-DD' CHANGELOG.md)
expected=$((all_headings - template_headings))
# Count the per-entry anchor ids, not the visible "Round N" text: React
# splits interpolated text with comment nodes, so the rendered markup
# reads `Round <!-- -->30` and a naive grep counts one.
rounds=$(curl -s "$BASE/log" | grep -o 'id="round-[^"]*"' | sort -u | wc -l | tr -d ' ')
if [ "$rounds" = "$expected" ]; then
  echo "ok    /log renders all $rounds rounds in CHANGELOG.md"
else
  echo "FAIL  /log renders $rounds rounds, CHANGELOG.md has $expected"
  failures=$((failures + 1))
fi

# RSS should carry one compact build-log item per parsed round. The guid
# prefix is deliberately distinct from the blog's permalink guid, so this
# remains true if the blog gains more posts later.
feed_rounds=$(curl -s "$BASE/feed.xml" | grep -c '<guid isPermaLink="false">addictedtoai:round:')
if [ "$feed_rounds" = "$expected" ]; then
  echo "ok    /feed.xml contains all $feed_rounds build-log rounds"
else
  echo "FAIL  /feed.xml contains $feed_rounds build-log rounds, CHANGELOG.md has $expected"
  failures=$((failures + 1))
fi

# The homepage advertises "N rounds say 'wrong'" and links that number
# to /log?q=wrong. The number is computed at build time from the parsed
# changelog; the search recomputes it in the browser from the rendered
# DOM. Two implementations of the same count is two chances to be wrong,
# and the failure mode is silent: a homepage promising 9 rounds and a
# search returning 6 discredits the page more than not showing a number
# at all. Recount from the rendered log here and require agreement.
echo
if node -e '
const [home, log] = process.argv.slice(1);
const fetchText = async (url) => (await fetch(url)).text();
(async () => {
  const homeHtml = await fetchText(home);
  const logHtml = await fetchText(log);

  // Only the rendered list -- everything after </ol> includes the RSC
  // payload, which repeats every entry and would match every term.
  const start = logHtml.search(/<ol\b[^>]*class="log-list"/);
  const list = logHtml.slice(start, logHtml.indexOf("</ol>", start));
  const entries = list
    .split(`<li class="log-entry"`)
    .slice(1)
    .map((e) => e.replace(/<[^>]*>/g, " ").toLowerCase());

  const links = [
    ...homeHtml.matchAll(/href="\/log\?q=([a-z]+)"><strong>(\d+)<\/strong>/g),
  ];
  if (links.length === 0) {
    console.log("FAIL  homepage advertises no round-mention counts");
    process.exitCode = 1;
    return;
  }

  let bad = 0;
  for (const [, term, claimed] of links) {
    const actual = entries.filter((e) => e.includes(term)).length;
    if (Number(claimed) === actual) {
      console.log(`ok    homepage says ${claimed} rounds say "${term}"; /log has ${actual}`);
    } else {
      console.log(`FAIL  homepage says ${claimed} rounds say "${term}", but /log has ${actual}`);
      bad++;
    }
  }
  // Setting exitCode rather than calling process.exit(): exiting from
  // inside this async callback while fetch sockets are still open trips
  // a libuv assertion on Windows and reports a false failure.
  process.exitCode = bad ? 1 : 0;
})();
' "$BASE/" "$BASE/log"; then
  :
else
  failures=$((failures + 1))
fi

# Every route in the sitemap must actually resolve. This is the check
# that would have caught a sitemap listing a page that no longer exists.
echo
for loc in $(curl -s "$BASE/sitemap.xml" | grep -o '<loc>[^<]*</loc>' | sed 's|</\?loc>||g'); do
  code=$(curl -s -o /dev/null -w '%{http_code}' "$loc")
  if [ "$code" = "200" ]; then
    echo "ok    sitemap entry $loc ($code)"
  else
    echo "FAIL  sitemap entry $loc -> $code"
    failures=$((failures + 1))
  fi
done

# The homepage, Blog, Demos, and Log all expose changelog-derived content.
# Their sitemap lastmod and the RSS channel's lastBuildDate should therefore
# agree with the newest dated changelog entry, not with the deploy clock.
echo
latest_date=$(grep '^### 20[0-9][0-9]-[0-9][0-9]-[0-9][0-9]$' CHANGELOG.md | head -1 | sed 's/^### //')
expected_freshness=$(node -e 'process.stdout.write(new Date(process.argv[1]).toISOString())' "$latest_date")
sitemap_body=$(curl -s "$BASE/sitemap.xml")
SITEMAP="$sitemap_body" BASE_URL="$BASE" EXPECTED="$expected_freshness" node <<'NODE'
const sitemap = process.env.SITEMAP;
const base = process.env.BASE_URL;
const expected = process.env.EXPECTED;
const paths = [base, `${base}/blog`, `${base}/demos`, `${base}/log`];
let failures = 0;
for (const path of paths) {
  const escaped = path.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = sitemap.match(
    new RegExp(`<url>\\s*<loc>${escaped}</loc>\\s*<lastmod>([^<]+)</lastmod>`)
  );
  if (match?.[1] === expected) {
    console.log(`ok    sitemap freshness ${path} (${expected})`);
  } else {
    console.log(`FAIL  sitemap freshness ${path} -> ${match?.[1] || "missing"} (want ${expected})`);
    failures++;
  }
}
process.exitCode = failures ? 1 : 0;
NODE
failures=$((failures + $?))

feed_last_build=$(curl -s "$BASE/feed.xml" | grep -o '<lastBuildDate>[^<]*</lastBuildDate>' | head -1)
if [ "$feed_last_build" = "<lastBuildDate>$(node -e 'process.stdout.write(new Date(process.argv[1]).toUTCString())' "$latest_date")</lastBuildDate>" ]; then
  echo "ok    feed freshness $feed_last_build"
else
  echo "FAIL  feed freshness $feed_last_build"
  failures=$((failures + 1))
fi

echo
if [ "$failures" -gt 0 ]; then
  echo "$failures check(s) failed"
  exit 1
fi
echo "all route checks passed"
