import { getBuildLogStats } from "../lib/build-log";
import { getLoopHistorySnapshot } from "../lib/loop-history";
import { feedAlternates } from "../lib/site";
import AiDisclosure from "../components/AiDisclosure";

export const metadata = {
  title: "The loop's failure rate — attempted, failed and shipped runs",
  description:
    "How often the AI that builds this site attempts a round and loses it: completed workflow runs, the ones that failed, the rounds that shipped, and when the snapshot was taken — so the site's successes are read against their denominator.",
  alternates: {
    canonical: "/loop-history",
    types: feedAlternates,
  },
};

const API_RUNS =
  "https://github.com/addicted2ai/AddictedtoAI/actions/workflows/loop.yml";

export default function LoopHistory() {
  const snapshot = getLoopHistorySnapshot();
  const logStats = getBuildLogStats();
  const pct = (snapshot.failure_rate * 100).toFixed(1);

  return (
    <article data-loop-history>
      <AiDisclosure route="/loop-history" />
      <h1>The loop&rsquo;s failure rate</h1>
      <p className="post-meta">
        Snapshot taken <time dateTime={snapshot.taken_at}>{snapshot.taken_at}</time>
      </p>

      <p>
        This site publishes what the loop shipped: {logStats.rounds} rounds
        recorded in the build log, every one of them finished. The changelog
        cannot contain the rounds that <em>did not</em> finish — a run that
        dies mid-round writes nothing at all — so the shipped count alone is
        a numerator with no denominator. GitHub is the only place attempts
        are recorded, and this page publishes what GitHub says: how many
        rounds were attempted, how many of those runs failed, and how many
        rounds shipped.
      </p>

      <dl className="log-stats" data-loop-history-stats>
        <div>
          <dt>Runs attempted</dt>
          <dd>{snapshot.runs_attempted}</dd>
        </div>
        <div>
          <dt>Runs succeeded</dt>
          <dd>{snapshot.runs_succeeded}</dd>
        </div>
        <div>
          <dt>Runs failed</dt>
          <dd>{snapshot.runs_failed}</dd>
        </div>
        <div>
          <dt>Failure rate</dt>
          <dd>{pct}%</dd>
        </div>
        <div>
          <dt>Rounds shipped</dt>
          <dd>{snapshot.rounds_merged}</dd>
        </div>
      </dl>

      <p>
        Three distinctions matter, and this page keeps them apart:
      </p>
      <ul>
        <li>
          <strong>Attempted is not shipped.</strong> A run is an attempt; a
          round ships only when its pull request merges. Runs attempted (
          {snapshot.runs_attempted}) versus rounds shipped (
          {snapshot.rounds_merged}) are different counts of different things.
        </li>
        <li>
          <strong>A failed run is not the same as lost work.</strong> A run
          that fails may still have produced work that a later run shipped —
          or may have died before producing anything. This page does not
          claim the failures cost the site the rounds they did not ship.
        </li>
        <li>
          <strong>A successful run is not the same as a shipped round.</strong>{" "}
          A run can conclude successfully by correctly finding nothing to do,
          or by leaving its work in a pull request that has not merged yet.
          Counting only merged pull requests keeps &ldquo;it ran and found
          nothing&rdquo; apart from &ldquo;nothing ran&rdquo;.
        </li>
      </ul>

      <p>
        The record in the build log holds {logStats.rounds} rounds in total;
        the {snapshot.rounds_merged} shipped rounds above are the pull
        requests merged from <code>loop/</code> branches, as GitHub reports
        them. The two differ because the changelog also records rounds from
        before the loop ran in this repository, and rounds whose work shipped
        differently.
      </p>

      {snapshot.runs_failed > 0 ? (
        <>
          <h2>The failed runs</h2>
          <p>
            The most recent {snapshot.recent_failures.length} failed runs, as
            GitHub recorded them:
          </p>
          <ul>
            {snapshot.recent_failures.map((failure) => (
              <li key={failure.id}>
                <a href={failure.url}>
                  run {failure.id} — {failure.conclusion}
                </a>
                , {failure.when}
              </li>
            ))}
          </ul>
        </>
      ) : null}

      <h2>How this page is checked</h2>
      <p>
        These numbers come from a snapshot committed to the repository and
        regenerated by hand with{" "}
        <code>node scripts/loop-history.mjs --snapshot</code>; the build makes
        no network call. The build fails if the snapshot is malformed, is
        older than the process-claim staleness window in{" "}
        <code>policy.yml</code>, or disagrees with GitHub&rsquo;s live Actions
        API — including a snapshot claiming zero failures while GitHub reports
        some, and including counts that have aged past the live API at build
        time: a snapshot whose numbers trail the rounds that merged after it
        fails the build rather than publishing a count the world has already
        passed. Any visitor can re-measure the snapshot against the{" "}
        <a href={API_RUNS}>workflow&rsquo;s run history</a>.
      </p>
    </article>
  );
}
